---
title: "child_trajectory_inference: human"
author: "Mohamed_Shoeb"
date: "10/13/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

## human tajectories
### abc
```{r}
## ---- run_slingshot_pca_abc
sim_abs <- slingshot(Embeddings(abs_neut_homo,  reduction = "pca")[,1:2])

ss_out_abs <- SlingshotDataSet(sim_abs)

ss_df_abs <- tidy_ss_output(ss_out_abs)  %>%
  mutate(curve1_lambda = max(curve1_lambda) - curve1_lambda,
         bin = cut(curve1_lambda/(max(curve1_lambda)/99),100) %>% as.integer,
         pseudotime = curve1_lambda/max(curve1_lambda)*100,
         #pseudotime_bin = round(pseudotime) %>% as.character(),
         pseudotime_bin = cut(pseudotime,112) %>% as.integer%>% as.character(),
         cell_type =  abs_neut_homo$cell_type[cell_id],
         tissue = abs_neut_homo$tissue[cell_id],
         group = abs_neut_homo$group[cell_id])  %>% 
  arrange(pseudotime) %>%
  mutate(pseudotime_bin = rep(seq_along(rle(pseudotime_bin)$values), rle(pseudotime_bin)$lengths) %>% as.character())

```

```{r abs_GAM, cache=TRUE}
#high expression genes (3 or more reads, in 5 or more cells)
top_expr_genes <- apply(abs_neut_homo@assays$SCT@counts>=3, 1, sum)
top_expr_genes <- names(top_expr_genes)[top_expr_genes>=5]
#exclude ribosomal and mitochondrial genes
model_genes <- str_subset(top_expr_genes, "^mt-|^r[prls]+[0-9]",negate = TRUE)
## ---- fit_tradeSeq_GAM_abs
sim_abs <- tradeSeq::fitGAM(abs_neut_homo@assays$SCT@counts[,ss_df_abs$cell_id],
                        pseudotime = ss_df_abs$curve1_lambda,
                        cellWeights = rep(1, nrow(ss_df_abs)),
                        genes = model_genes,
                        nknots = 6
                        )

assoc_res_abs <- associationTest(sim_abs
                                 )
```

Aggregated heatmaps
```{r}
aggr_avg_abs <- aggr_pseud_avg(seurat_obj=abs_neut_homo,
                                ss_df=ss_df_abs,
                                genes=diff_traj$gene_symbol)

aggr_avg_abs_scaled <- aggr_avg_abs %>% 
  t() %>% 
  scale() %>% 
  t() %>% 
  as.data.frame() %>% 
  mutate_all(~ ifelse(abs(.)>2.5, 2.5* ./abs(.),.))

aggr_bin_abs_annot <- ss_df_abs %>% 
  filter(pseudotime_bin %in% colnames(aggr_avg_abs)) %>% 
  group_by(pseudotime_bin,cell_type ) %>% 
  summarize(n = n()) %>% 
  ungroup(cell_type ) %>% 
  slice_max(n,  with_ties = FALSE) %>% 
  ungroup() %>% 
  arrange(as.numeric(pseudotime_bin))
```


Figure 7 top panel
```{r}
fig_5_abs <- ggplot(ss_df_abs)+
  ggrastr::geom_point_rast(aes(PC_1, PC_2),
             size = 1.3, color = "black")+
  ggrastr::geom_point_rast(aes(PC_1, PC_2, color = pseudotime),
             size = 1)+
  geom_path(aes(curve1_PC_1, curve1_PC_2))+
  viridis::scale_color_viridis(option = "A", breaks = c(0, 100))+
  labs(x = "PC_1", y =  "PC_2", subtitle = glue::glue("Xie 2022 (n = {scales::comma(nrow(ss_df_abs))} cells)"))+
    guides(color = guide_colourbar(title = "Pseudotime", title.position = "top", direction = "horizontal"))+
  theme(legend.position = c(0.05,0.93))
```

### Suo
```{r}
## ---- run_slingshot_pca
sim_suo_neut_homo <- slingshot(Embeddings(suo_neut_homo,  reduction = "pca")[,1:2])

ss_out_suo_neut_homo <- SlingshotDataSet(sim_suo_neut_homo)

ss_df_suo_neut <- tidy_ss_output(ss_out_suo_neut_homo)  %>%
  mutate(pseudotime = curve1_lambda/max(curve1_lambda)*100,
         pseudotime_bin = cut(pseudotime,102) %>% as.integer%>% as.character(),
         cell_type =  suo_neut_homo$celltype_annotation[cell_id],
         organ = suo_neut_homo$organ[cell_id])  %>% 
  arrange(pseudotime) %>%
  mutate(pseudotime_bin = rep(seq_along(rle(pseudotime_bin)$values), rle(pseudotime_bin)$lengths) %>% as.character())
  
#only BM
sim_suo_neut_homo_bm  <- slingshot(Embeddings(subset(suo_neut_homo,organ %in% c("BM")),
                                   reduction = "pca")[,1:2],
                                   clusterLabels = subset(suo_neut_homo,organ %in% c("BM"))$celltype_annotation,
                                   start.clus = "PROMYELOCYTE",
                                   end.clus = "NEUTROPHIL")

ss_out_suo_neut_homo_bm <- SlingshotDataSet(sim_suo_neut_homo_bm )

ss_df_suo_neut_bm <- tidy_ss_output(ss_out_suo_neut_homo_bm) %>%
  mutate(pseudotime = curve1_lambda/max(curve1_lambda)*100,
         pseudotime_bin = cut(pseudotime,102) %>% as.integer%>% as.character(),
         cell_type =  suo_neut_homo$celltype_annotation[cell_id],
         organ = suo_neut_homo$organ[cell_id])  %>% 
  arrange(pseudotime) %>%
  mutate(pseudotime_bin = rep(seq_along(rle(pseudotime_bin)$values), rle(pseudotime_bin)$lengths) %>% as.character())

#only BM
ss_df_suo_neut_bm_2 <- tidy_ss_output(ss_out_suo_neut_homo) %>%
  mutate(cell_type =  suo_neut_homo$celltype_annotation[cell_id],
         organ = suo_neut_homo$organ[cell_id]) %>%
  filter(organ %in% c("BM"))%>%
  mutate(pseudotime = curve1_lambda/max(curve1_lambda)*100,
         #pseudotime_bin = round(pseudotime) %>% as.character(),
         pseudotime_bin = cut(pseudotime,102) %>% as.integer%>% as.character()) %>% 
  arrange(pseudotime) %>%
  mutate(pseudotime_bin = rep(seq_along(rle(pseudotime_bin)$values), rle(pseudotime_bin)$lengths) %>% as.character())

```

```{r}
aggr_avg_suo <- aggr_pseud_avg(seurat_obj=suo_neut_homo,
                                ss_df=ss_df_suo_neut,
                                genes=diff_traj$gene_symbol)


aggr_bin_suo_annot <- ss_df_suo_neut %>% 
  filter(pseudotime_bin %in% colnames(aggr_avg_suo)) %>% 
  group_by(pseudotime_bin,cell_type ) %>% 
  summarize(n = n()) %>% 
  ungroup(cell_type ) %>% 
  slice_max(n,  with_ties = FALSE) %>% 
  ungroup() %>% 
  arrange(as.numeric(pseudotime_bin))

#only BM
aggr_avg_suo_bm <- aggr_pseud_avg(seurat_obj=suo_neut_homo,
                                ss_df=ss_df_suo_neut_bm,
                                genes=diff_traj$gene_symbol)


aggr_bin_suo_bm_annot <- ss_df_suo_neut_bm %>% 
  filter(pseudotime_bin %in% colnames(aggr_avg_suo_bm)) %>% 
  group_by(pseudotime_bin,cell_type ) %>% 
  summarize(n = n()) %>% 
  ungroup(cell_type ) %>% 
  slice_max(n,  with_ties = FALSE) %>% 
  ungroup() %>% 
  arrange(as.numeric(pseudotime_bin))
```


Figure 7 top panel
```{r}
fig_5_suo <- ggplot(ss_df_suo_neut_bm)+
  ggrastr::geom_point_rast(aes(PC_1, PC_2),
             size = 1.3, color = "black")+
  ggrastr::geom_point_rast(aes(PC_1, PC_2, color = pseudotime),
             size = 1)+
  geom_path(aes(curve1_PC_1, curve1_PC_2))+
  viridis::scale_color_viridis(option = "A", breaks = c(0, 100))+
  guides(color = guide_colourbar(title = "Pseudotime", title.position = "top", direction = "horizontal"))+
  labs(x = "PC_1", y =  "PC_2", subtitle = glue::glue("Suo 2022 (n = {scales::comma(nrow(ss_df_suo_neut_bm))} cells)"))+
  scale_y_continuous(expand = expansion(add = c(1,2.5)))
```

### tabula sapiens
```{r}
sim_tabula_sapiens_neut_homo <- slingshot(Embeddings(tabula_sapiens_neut_homo,  reduction = "pca")[,1:2],
                                   clusterLabels = tabula_sapiens_neut_homo$tissue_in_publication,
                                   start.clus = "Bone_Marrow",
                                   end.clus = "Trachea", extend = "n")

ss_out_tabula_sapiens_neut_homo <- SlingshotDataSet(sim_tabula_sapiens_neut_homo)

ss_df_tabula_sapiens_neut <- tidy_ss_output(ss_out_tabula_sapiens_neut_homo)  %>% 
  mutate(curve1_lambda = max(curve1_lambda) - curve1_lambda,
         pseudotime = curve1_lambda/max(curve1_lambda)*100,
         pseudotime_bin = cut(pseudotime,100) %>% as.integer%>% as.character(),
         cell_type =  tabula_sapiens_neut_homo$cell_type[cell_id],
         tissue = tabula_sapiens_neut_homo$tissue[cell_id])  %>% 
  arrange(pseudotime) %>%
  mutate(pseudotime_bin = rep(seq_along(rle(pseudotime_bin)$values), rle(pseudotime_bin)$lengths) %>% as.character())

#only BM
ss_df_tabula_sapiens_neut_bm <- tidy_ss_output(ss_out_tabula_sapiens_neut_homo)  %>% 
  mutate(tissue = tabula_sapiens_neut_homo$tissue[cell_id]) %>%
  filter(tissue == "bone marrow") %>% 
  mutate(pseudotime = curve1_lambda/max(curve1_lambda)*100,
         pseudotime_bin = cut(pseudotime,107) %>% as.integer%>% as.character(),
         cell_type =  tabula_sapiens_neut_homo$cell_type[cell_id])  %>% 
  arrange(pseudotime) %>%
  mutate(pseudotime_bin = rep(seq_along(rle(pseudotime_bin)$values), rle(pseudotime_bin)$lengths) %>% as.character())
```

```{r}
aggr_avg_tabula_sapiens <- aggr_pseud_avg(seurat_obj=tabula_sapiens_neut_homo,
                                ss_df=ss_df_tabula_sapiens_neut,
                                genes=diff_traj$gene_symbol)


aggr_bin_tabula_sapiens_annot <- ss_df_tabula_sapiens_neut %>% 
  filter(pseudotime_bin %in% colnames(aggr_avg_tabula_sapiens)) %>% 
  group_by(pseudotime_bin,tissue ) %>% 
  summarize(n = n()) %>% 
  ungroup(tissue ) %>% 
  slice_max(n,  with_ties = FALSE) %>% 
  ungroup() %>% 
  arrange(as.numeric(pseudotime_bin))

#only BM
aggr_avg_tabula_sapiens_bm <- aggr_pseud_avg(seurat_obj=tabula_sapiens_neut_homo,
                                ss_df=ss_df_tabula_sapiens_neut_bm,
                                genes=diff_traj$gene_symbol)


aggr_bin_tabula_sapiens_bm_annot <- ss_df_tabula_sapiens_neut_bm %>% 
  filter(pseudotime_bin %in% colnames(aggr_avg_tabula_sapiens)) %>% 
  group_by(pseudotime_bin,tissue ) %>% 
  summarize(n = n()) %>% 
  ungroup(tissue ) %>% 
  slice_max(n,  with_ties = FALSE) %>% 
  ungroup() %>% 
  arrange(as.numeric(pseudotime_bin))
```


Figure 7 top panel
```{r}
fig_5_tabula_sapiens <- ggplot(ss_df_tabula_sapiens_neut_bm)+
  ggrastr::geom_point_rast(aes(PC_1, PC_2),
             size = 1.3, color = "black")+
  ggrastr::geom_point_rast(aes(PC_1, PC_2, color = pseudotime),
             size = 1)+
  geom_path(aes(curve1_PC_1, curve1_PC_2))+
  viridis::scale_color_viridis(option = "A", breaks = c(0, 100))+
  guides(color = guide_colourbar(title = "Pseudotime", title.position = "top", direction = "horizontal"))+
  labs(x = "PC_1", y =  "PC_2", subtitle = glue::glue("Tabula Sapiens 2022 (n = {scales::comma(nrow(ss_df_tabula_sapiens_neut_bm))} cells)"))+
  scale_y_continuous(expand = expansion(add = c(1,2.5)))
```

### ramirez
```{r}
#FPKM values were normalized for batch effects using Combat
ramirez_norm <- ramirez_count_homo %>% 
  filter(gene_name_zfin %in% diff_traj$gene_symbol) %>% 
  column_to_rownames("gene_name_zfin") %>% 
  mutate_all(~log2(.x+1)) 
ramirez_norm <- ramirez_norm[apply(ramirez_norm,1,var)>0,]

ramirez_scaled <- t(ramirez_norm) %>% scale %>% t() %>% as.data.frame
ramirez_scaled <- apply(ramirez_scaled, 2, function(x){
  ifelse(abs(x)>1.5, 1.5* x/abs(x),x)
  })
```
