---
title: "child_trajectory_inference: mouse"
author: "Mohamed_Shoeb"
date: "10/13/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Mouse trajectories
### xie trajectory
Slingshot trajectory inference 
```{r}
## ---- run_slingshot_pca_xie
sim_xie <- slingshot(Embeddings(xie_mm_neut_homo,  reduction = "pca")[,1:2])

ss_out_xie <- SlingshotDataSet(sim_xie)

ss_df_xie <- tidy_ss_output(ss_out_xie) %>%
  mutate(curve1_lambda = max(curve1_lambda) - curve1_lambda,
         pseudotime = curve1_lambda/max(curve1_lambda)*100,
         #pseudotime_bin = round(pseudotime) %>% as.character(),
         pseudotime_bin = cut(pseudotime,103) %>% as.integer%>% as.character(),
         Phase =  xie_mm_neut_homo$Phase[cell_id],
         cluster_xie = xie_mm_neut_homo$cluster[cell_id],
         tissue = xie_mm_neut_homo$tissue[cell_id]) %>% 
  arrange(pseudotime) %>%
  mutate(pseudotime_bin = rep(seq_along(rle(pseudotime_bin)$values), rle(pseudotime_bin)$lengths) %>% as.character())

#only BM
sim_xie_bm <- slingshot(Embeddings(subset(xie_mm_neut_homo,tissue %in% c("WT_BM", "WT_BM_C-kit+Gr1")),
                                reduction = "pca")[,1:2])

ss_out_xie_bm <- SlingshotDataSet(sim_xie_bm)

ss_df_xie_bm <- tidy_ss_output(ss_out_xie_bm)  %>%
  mutate(curve1_lambda = max(curve1_lambda) - curve1_lambda,
         pseudotime = curve1_lambda/max(curve1_lambda)*100,
         #pseudotime_bin = round(pseudotime) %>% as.character(),
         pseudotime_bin = cut(pseudotime,105) %>% as.integer%>% as.character(),
         Phase =  xie_mm_neut_homo$Phase[cell_id],
         cluster_xie = xie_mm_neut_homo$cluster[cell_id],
         tissue = xie_mm_neut_homo$tissue[cell_id]) %>% 
  arrange(pseudotime) %>%
  mutate(pseudotime_bin = rep(seq_along(rle(pseudotime_bin)$values), rle(pseudotime_bin)$lengths) %>% as.character())

#only BM2
ss_df_xie_bm_2 <- tidy_ss_output(ss_out_xie) %>%
  mutate(Phase =  xie_mm_neut_homo$Phase[cell_id],
         cluster_xie = xie_mm_neut_homo$cluster[cell_id],
         tissue = xie_mm_neut_homo$tissue[cell_id]) %>%
  filter(tissue %in% c("WT_BM", "WT_BM_C-kit+Gr1"))%>%
  mutate(curve1_lambda = max(curve1_lambda) - curve1_lambda,
         pseudotime = curve1_lambda/max(curve1_lambda)*100,
         #pseudotime_bin = round(pseudotime) %>% as.character(),
         pseudotime_bin = cut(pseudotime,104) %>% as.integer%>% as.character()) %>% 
  arrange(pseudotime) %>%
  mutate(pseudotime_bin = rep(seq_along(rle(pseudotime_bin)$values), rle(pseudotime_bin)$lengths) %>% as.character())
```

```{r xie_GAM, cache=TRUE}
## ---- fit_tradeSeq_GAM_xie
#high expression genes (3 or more reads, in 5 or more cells)
top_expr_genes <- apply(xie_mm_neut_homo@assays$SCT@counts>=3, 1, sum)
top_expr_genes <- names(top_expr_genes)[top_expr_genes>=5]
#exclude ribosomal and mitochondrial genes
model_genes <- str_subset(top_expr_genes, "^mt-|^r[prls]+[0-9]",negate = TRUE)
sim_xie <- tradeSeq::fitGAM(xie_mm_neut_homo@assays$SCT@counts[,ss_df_xie$cell_id],
                        pseudotime = ss_df_xie$curve1_lambda,
                        cellWeights = rep(1, nrow(ss_df_xie)),
                        genes = model_genes,
                        nknots = 6
                        )

assoc_res_xie <- associationTest(sim_xie)
```

Aggregated heatmaps
```{r}
aggr_avg_xie <- aggr_pseud_avg(seurat_obj=xie_mm_neut_homo,
                                 ss_df=ss_df_xie,
                                 genes=diff_traj$gene_symbol)

aggr_avg_xie_scaled <- aggr_avg_xie %>% 
  t() %>% 
  scale() %>% 
  t() %>% 
  as.data.frame() %>% 
  mutate_all(~ ifelse(abs(.)>2.5, 2.5* ./abs(.),.))

aggr_bin_xie_annot <- ss_df_xie %>% 
  filter(pseudotime_bin %in% colnames(aggr_avg_xie)) %>% 
  group_by(pseudotime_bin,cluster_xie) %>% 
  summarize(n = n()) %>% 
  ungroup(cluster_xie) %>%
  slice_max(n,  with_ties = FALSE) %>% 
  arrange(as.numeric(pseudotime_bin)) %>% 
  ungroup()

#only BM
aggr_avg_xie_bm <- aggr_pseud_avg(seurat_obj=xie_mm_neut_homo,
                                 ss_df=ss_df_xie_bm,
                                 genes=diff_traj$gene_symbol)

aggr_bin_xie_bm_annot<- ss_df_xie_bm %>% 
  filter(pseudotime_bin %in% colnames(aggr_avg_xie_bm)) %>% 
  group_by(pseudotime_bin,tissue) %>% 
  summarize(n = n()) %>% 
  ungroup(tissue) %>%
  slice_max(n,  with_ties = FALSE) %>% 
  arrange(as.numeric(pseudotime_bin))%>% 
  ungroup()
```

Figure 7 top panel
```{r}
#manuscript figures
fig_5_xie <- ggplot(ss_df_xie_bm)+
  ggrastr::geom_point_rast(aes(PC_1, PC_2),
             size = 1.3, color = "black")+
  ggrastr::geom_point_rast(aes(PC_1, PC_2, color = pseudotime),
             size = 1)+
  geom_path(aes(curve1_PC_1, curve1_PC_2))+
  viridis::scale_color_viridis(option = "A", breaks = c(0, 100))+
    guides(color = guide_colourbar(title = "Pseudotime", title.position = "top", direction = "horizontal"))+
  labs(x = "PC_1", y =  "PC_2", subtitle = glue::glue("Xie 2020 (n = {scales::comma(nrow(ss_df_xie_bm))} cells)"))+
  theme(legend.position = c(0.05,0.93))
```

### neutrotime
```{r}
## ---- run_slingshot_pca_abc
sim_neutime <- slingshot(Embeddings(neutime_obj_homo,  reduction = "pca_scPortal")[,1:2])

ss_out_neutime <- SlingshotDataSet(sim_neutime)

ss_df_neutime <- tidy_ss_output(ss_out_neutime) %>% 
  mutate(pseudotime = curve1_lambda/max(curve1_lambda)*100,
         #pseudotime_bin = round(pseudotime) %>% as.character(),
         pseudotime_bin = cut(pseudotime,100) %>% as.integer%>% as.character(),
         experiment =  neutime_obj_homo$experiment_extract[cell_id],
         tissue = neutime_obj_homo$tissue_extract[cell_id],
         dataset = neutime_obj_homo$dataset_extract[cell_id],
         neutrotime = neutime_obj_homo$neutrotime[cell_id],
         maturation_score = neutime_obj_homo$maturation_score[cell_id]) %>% 
  arrange(pseudotime) %>%
  mutate(pseudotime_bin = rep(seq_along(rle(pseudotime_bin)$values), rle(pseudotime_bin)$lengths) %>% as.character())

#only BM
sim_neutime_bm <- slingshot(Embeddings(subset(neutime_obj_homo,tissue %in% c("marrow")),
                                reduction = "pca_scPortal")[,1:2])

ss_out_neutime_bm <- SlingshotDataSet(sim_neutime_bm)

ss_df_neutime_bm <- tidy_ss_output(ss_out_neutime_bm) %>% 
  mutate(curve1_lambda = max(curve1_lambda) - curve1_lambda,
         pseudotime = curve1_lambda/max(curve1_lambda)*100,
         #pseudotime_bin = round(pseudotime) %>% as.character(),
         pseudotime_bin = cut(pseudotime,100) %>% as.integer%>% as.character(),
         experiment =  neutime_obj_homo$experiment_extract[cell_id],
         tissue = neutime_obj_homo$tissue_extract[cell_id],
         dataset = neutime_obj_homo$dataset_extract[cell_id],
         neutrotime = neutime_obj_homo$neutrotime[cell_id],
         maturation_score = neutime_obj_homo$maturation_score[cell_id]) %>% 
  arrange(pseudotime) %>%
  mutate(pseudotime_bin = rep(seq_along(rle(pseudotime_bin)$values), rle(pseudotime_bin)$lengths) %>% as.character())
#only BM2
ss_df_neutime_bm_2 <- tidy_ss_output(ss_out_neutime) %>%
  mutate(experiment =  neutime_obj_homo$experiment_extract[cell_id],
         tissue = neutime_obj_homo$tissue_extract[cell_id],
         dataset = neutime_obj_homo$dataset_extract[cell_id],
         neutrotime = neutime_obj_homo$neutrotime[cell_id],
         maturation_score = neutime_obj_homo$maturation_score[cell_id]) %>%
  filter(tissue %in% c("BM"))%>%
  mutate(pseudotime = curve1_lambda/max(curve1_lambda)*100,
         #pseudotime_bin = round(pseudotime) %>% as.character(),
         pseudotime_bin = cut(pseudotime,104) %>% as.integer%>% as.character()) %>% 
  arrange(pseudotime) %>%
  mutate(pseudotime_bin = rep(seq_along(rle(pseudotime_bin)$values), rle(pseudotime_bin)$lengths) %>% as.character())

```

```{r neutime_GAM, cache=TRUE}
#high expression genes (3 or more reads, in 5 or more cells)
top_expr_genes <- apply(neutime_obj_homo@assays$SCT@counts>=3, 1, sum)
top_expr_genes <- names(top_expr_genes)[top_expr_genes>=5]
#exclude ribosomal and mitochondrial genes
model_genes <- str_subset(top_expr_genes, "^mt-|^r[prls]+[0-9]",negate = TRUE)
pseudot_traj <- slingPseudotime(sim_neutime, na=FALSE)
cellWeights <- slingCurveWeights(sim_neutime)

## ---- fit_tradeSeq_GAM_abs
sim_neutime <- tradeSeq::fitGAM(neutime_obj_homo@assays$SCT@counts[,ss_df_neutime$cell_id],
                        pseudotime = ss_df_neutime$curve1_lambda,
                        cellWeights = rep(1,nrow(ss_df_neutime)),
                        genes = model_genes,
                        nknots = 6
                        )

assoc_res_neutime <- associationTest(sim_neutime
                                 )
```

Aggregated heatmaps
```{r}
aggr_avg_neutime <- aggr_pseud_avg(seurat_obj=neutime_obj_homo,
                                 ss_df=ss_df_neutime,
                                 genes=diff_traj$gene_symbol)

aggr_avg_neutime_scaled <- aggr_avg_neutime %>% 
  t() %>% 
  scale() %>% 
  t() %>% 
  as.data.frame() %>% 
  mutate_all(~ ifelse(abs(.)>2.5, 2.5* ./abs(.),.))

aggr_bin_neutime_annot <- ss_df_neutime %>% 
  filter(pseudotime_bin %in% colnames(aggr_avg_neutime)) %>% 
  group_by(pseudotime_bin,tissue) %>% 
  summarize(n = n()) %>% 
  ungroup(tissue) %>% 
  slice_max(n,  with_ties = FALSE) %>% 
  ungroup() %>% 
  arrange(as.numeric(pseudotime_bin))

#only BM
aggr_avg_neutime_bm <- aggr_pseud_avg(seurat_obj=neutime_obj_homo,
                                 ss_df=ss_df_neutime_bm,
                                 genes=diff_traj$gene_symbol)

aggr_bin_neutime_bm_annot <- ss_df_neutime_bm %>% 
  filter(pseudotime_bin %in% colnames(aggr_avg_neutime_bm)) %>% 
  group_by(pseudotime_bin,tissue) %>% 
  summarize(n = n()) %>% 
  ungroup(tissue) %>%
  slice_max(n,  with_ties = FALSE) %>% 
  arrange(as.numeric(pseudotime_bin))%>% 
  ungroup()
```

Figure 7 top panel
```{r}
fig_5_neutime <- ggplot(ss_df_neutime_bm)+
  ggrastr::geom_point_rast(aes(scPC_1, scPC_2),
             size = 1.3, color = "black")+
  ggrastr::geom_point_rast(aes(scPC_1, scPC_2, color = pseudotime),
             size = 1)+
  geom_path(aes(curve1_scPC_1, curve1_scPC_2))+
  viridis::scale_color_viridis(option = "A", breaks = c(0, 100))+
  guides(color = guide_colourbar(title = "Pseudotime", title.position = "top", direction = "horizontal"))+
  labs(x = "PC_1", y =  "PC_2", subtitle = glue::glue("Grieshaber-Bouyer 2020 (n = {scales::comma(nrow(ss_df_neutime_bm))} cells)"))+
  scale_y_continuous(expand = expansion(add = c(1,2.5)))+
  theme(legend.position = c(0.05,0.93))
```


### ballesteros
```{r}
## ---- run_slingshot_pca_abc
sim_ballesteros  <- slingshot(Embeddings(ballesteros_obj_neut_homo,reduction = "pca")[,1:2])

ss_out_ballesteros <- SlingshotDataSet(sim_ballesteros)

ss_df_ballesteros <- tidy_ss_output(ss_out_ballesteros) %>% 
  mutate(curve1_lambda = max(curve1_lambda) - curve1_lambda,
         pseudotime = curve1_lambda/max(curve1_lambda)*100,
         #pseudotime_bin = round(pseudotime) %>% as.character(),
         pseudotime_bin = cut(pseudotime,102) %>% as.integer%>% as.character(),
         tissue = ballesteros_obj_neut_homo$tissue[cell_id],
         orig.ident = ballesteros_obj_neut_homo$orig.ident[cell_id]) %>% 
  arrange(pseudotime) %>%
  mutate(pseudotime_bin = rep(seq_along(rle(pseudotime_bin)$values), rle(pseudotime_bin)$lengths) %>% as.character())

#only BM
sim_ballesteros_bm <- slingshot(Embeddings(subset(ballesteros_obj_neut_homo,tissue %in% c("BM")),
                                reduction = "pca")[,1:2])

ss_out_ballesteros_bm <- SlingshotDataSet(sim_ballesteros_bm)

ss_df_ballesteros_bm <- tidy_ss_output(ss_out_ballesteros_bm) %>% 
  mutate(curve1_lambda = max(curve1_lambda) - curve1_lambda,
         pseudotime = curve1_lambda/max(curve1_lambda)*100,
         #pseudotime_bin = round(pseudotime) %>% as.character(),
         pseudotime_bin = cut(pseudotime,102) %>% as.integer%>% as.character(),
         tissue = ballesteros_obj_neut_homo$tissue[cell_id],
         orig.ident = ballesteros_obj_neut_homo$orig.ident[cell_id]) %>% 
  arrange(pseudotime) %>%
  mutate(pseudotime_bin = rep(seq_along(rle(pseudotime_bin)$values), rle(pseudotime_bin)$lengths) %>% as.character())

#only BM2
ss_df_ballesteros_bm_2 <- tidy_ss_output(ss_out_ballesteros) %>%
  mutate(tissue = ballesteros_obj_neut_homo$tissue[cell_id],
         orig.ident = ballesteros_obj_neut_homo$orig.ident[cell_id]) %>%
  filter(tissue %in% c("BM"))%>%
  mutate(curve1_lambda = max(curve1_lambda) - curve1_lambda,
         pseudotime = curve1_lambda/max(curve1_lambda)*100,
         #pseudotime_bin = round(pseudotime) %>% as.character(),
         pseudotime_bin = cut(pseudotime,106) %>% as.integer%>% as.character()) %>% 
  arrange(pseudotime) %>%
  mutate(pseudotime_bin = rep(seq_along(rle(pseudotime_bin)$values), rle(pseudotime_bin)$lengths) %>% as.character())

```

```{r ballesteros_GAM, cache=TRUE}
#high expression genes (3 or more reads, in 5 or more cells)
top_expr_genes <- apply(ballesteros_obj_neut_homo@assays$SCT@counts>=3, 1, sum)
top_expr_genes <- names(top_expr_genes)[top_expr_genes>=5]
#exclude ribosomal and mitochondrial genes
model_genes <- str_subset(top_expr_genes, "^mt-|^r[prls]+[0-9]",negate = TRUE)
pseudot_traj <- slingPseudotime(sim_ballesteros, na=FALSE)
cellWeights <- slingCurveWeights(sim_ballesteros)

## ---- fit_tradeSeq_GAM_abs
sim_ballesteros <- tradeSeq::fitGAM(ballesteros_obj_neut_homo@assays$SCT@counts[,ss_df_ballesteros$cell_id],
                        pseudotime = ss_df_ballesteros$curve1_lambda,
                        cellWeights = rep(1,nrow(ss_df_ballesteros)),
                        genes = model_genes,
                        nknots = 6
                        )

assoc_res_ballesteros <- associationTest(sim_ballesteros,
                                 )

```

Figure 7 top panel
```{r}
fig_5_ballesteros <- ggplot(ss_df_ballesteros_bm)+
  ggrastr::geom_point_rast(aes(PC_1, PC_2),
             size = 1.3, color = "black")+
  ggrastr::geom_point_rast(aes(PC_1, PC_2, color = pseudotime),
             size = 1)+
  geom_path(aes(curve1_PC_1, curve1_PC_2))+
  annotate(geom = "text",
         size = 4,
         label = glue("n = {scales::comma(nrow(ss_df_ballesteros))} cells"),
         x = min(ss_df_ballesteros$PC_1), y = max(ss_df_ballesteros$PC_2),
         hjust = 0)+
  viridis::scale_color_viridis(option = "A", breaks = c(0, 100))+
  labs(x = "PC_1", y =  "PC_2", subtitle = glue::glue("Ballesteros 2020 (n = {scales::comma(nrow(ss_df_ballesteros_bm))} cells)"))+
  guides(color = guide_colourbar(title = "Pseudotime", title.position = "top", direction = "horizontal"))+
  theme(legend.position = c(0.05,0.93))

```

Aggregated heatmaps
```{r}
aggr_avg_ballesteros <- aggr_pseud_avg(seurat_obj=ballesteros_obj_neut_homo,
                                 ss_df=ss_df_ballesteros,
                                 genes=diff_traj$gene_symbol)

aggr_avg_ballesteros_scaled <- aggr_avg_ballesteros %>% 
  t() %>% 
  scale() %>% 
  t() %>% 
  as.data.frame() %>% 
  mutate_all(~ ifelse(abs(.)>2.5, 2.5* ./abs(.),.))

aggr_bin_ballesteros_annot <- ss_df_ballesteros %>% 
  filter(pseudotime_bin %in% colnames(aggr_avg_ballesteros)) %>% 
  group_by(pseudotime_bin,tissue) %>% 
  summarize(n = n()) %>% 
  ungroup(tissue) %>% 
  slice_max(n,  with_ties = FALSE) %>% 
  ungroup() %>% 
  arrange(as.numeric(pseudotime_bin))

#only BM
aggr_avg_ballesteros_bm <- aggr_pseud_avg(seurat_obj=ballesteros_obj_neut_homo,
                                 ss_df=ss_df_ballesteros_bm,
                                 genes=diff_traj$gene_symbol)

aggr_bin_ballesteros_bm_annot <- ss_df_ballesteros_bm %>% 
  filter(pseudotime_bin %in% colnames(aggr_avg_ballesteros_bm)) %>% 
  group_by(pseudotime_bin,tissue) %>% 
  summarize(n = n()) %>% 
  ungroup(tissue) %>%
  slice_max(n,  with_ties = FALSE) %>% 
  arrange(as.numeric(pseudotime_bin))%>% 
  ungroup()
```

### Evrard
```{r}
evrard_norm_homo_scaled <- t(evrard_norm_homo) %>% scale %>% t() %>% as.data.frame
evrard_norm_homo_scaled <- apply(evrard_norm_homo_scaled, 2, function(x){
  ifelse(abs(x)>1.5, 1.5* x/abs(x),x)
  })
o <- seriate(aggr_avg_traj_scaled, method = "PCA")

gene_order_evrard<- intersect(names(get_order(o))[get_order(o)],rownames(evrard_norm_homo_scaled))
  
column_annot <- ComplexHeatmap::HeatmapAnnotation(stage=str_replace(colnames(evrard_norm_homo),"_.$",""))
ComplexHeatmap::Heatmap(evrard_norm_homo_scaled[gene_order_evrard,],
                        col =  colorRampPalette( grDevices::hcl.colors(9,"RdYlBu"))(100) %>% rev(),
                      cluster_columns=FALSE,
                      cluster_rows=FALSE,
                      show_row_names=TRUE,
                      show_column_names=TRUE,
                      top_annotation = column_annot,
                      column_title = glue(""))
```
